### ISSUE TITLE
Bug in AsmFish from 15.02.18  , (The newest Master)

### ISSUE THREAD

**Issue by ghost** [lantonov/asmFish#113]
hi,
I think there is a bug in the Asmfish Master from 15.02.18 !
It was switched to the OTM. Which is alright. But if I want to change the MinThinkTime in Arena under Settings, for example, from 20ms to maybe 400ms or another value under 1 sec. Then you can do that and the value will also be displayed, but during the game the value always stays 20ms. I recognize that by the low depth per move. For example, the depth at 20ms is 10 deep, at 400ms it's 18 (which I see in other engines) deep. So when I set 400ms, the depth is still 10. Also in the uci.asm I changed the value, but nothing changes. Do you know how to fix the bug? I am using Windows 64 bit  _popcnt version. Thank you in advance.

**Comment by lantonov** [comment]
Hi Justin,
The option Minimum Thinking Time was restored with the latest patch which restored the old time management. It is not as important as Slow Mover and Move Overhead, the other options that were restored. A brief look comparing the SF and asmFish implementations didn't find any inconstistencies but I have to do some more tests later. It is also possible that this option is overriden by the other more important options when needed.

**Comment by ghost** [comment]
Hi lantonov,
First of thanks for your error analysis. You have found the cause. But I like to play tournaments with the other newest engines (Brainfish, Cfish, Stockfish and Sugarxpro). I would also like to take the Asmfish. I then set a minthinktime for all engines under one second. At least (with 4 cores with i5-3450) an acceptable playing power comes out about 2-4 million knots and a depth of 18. The advantage for me is that I can play a lot of games in quick time and that appeals to me very much. Unfortunately I can not play with the Asmfish any more and he has no meaning for me anymore. Why do not you take theOTM from the last Asmfish_2017-08-14_popcnt? I myself tried to swap the sourcedfiles Checktime.asm, Maindata.asm, Structs.asm, TimeMng.asm and Uci.asm but got errors when compiling. My request to you is, see that you activate the MinThinkingTime again or the Asmfis is unfortunately not more downloaded from me.Thanks. justine.

**Comment by CounterPly** [comment]
Hi jjustine,

Are you certain the problem is with the MinThinkTime parameter? It seems to be working fine for me in the Fritz 16 GUI. In Engine vs Engine matches (on PlayChess), I notice a considerable difference between MinThinkTime settings of 20 and 120 (it would be nice if someone could confirm this though to ensure this isn't a placebo on my part).

 As lantonov mentioned, the Slow Mover and Move Overhead parameters are more important than MinThinkTime when it comes to optimizing depth/move. I'll try to conduct some tests in Arena later this evening to see if I can replicate this strange behavior you are observing. In the meantime, perhaps Mohammed will notice a glaring bug in the latest TM patch I pushed, but as far as I can tell, it should be identical in functionality to the time management in your referenced asmFish build from August 14, 2017.

**Comment by ghost** [comment]
Hi Counterplay,
It is not at Arena 3.5.1, but in my opinion at the source of Asmfish_15-02-18! With all other engines (Brainfish, Cfish, Stockfisch, Sugarxpro and also Asmfish_2017-08-14) the conversion of the MinThinkTime works perfectly. I have also made some games asmfish_2017-08-14 against the new asmfish_15.02. If both have 20 ms, the result is very close. But if I put both on 400ms then Asmfish_15.02 loses high.
For this I have inserted two log.files. first 187.png. Both engines have set 400ms. On the right side under depth you can see that Asmfish_2017-08-14 counts with 18-19 depth and Asmfish_15.02 only counts with 11-12 depth. The result of 19.0: 1.0 for Asmfish_2017-08-14 is clear proof. The other logfile (188) have both motors set 20ms. Both expect a depth of 11-12 which is ok..Asmfish_2017-08-14 wins 11: 9.

Engine-Match Montag, 19. Februar 2018 07:55:51
Paarung 1/1 :    AsmFishW_2017-08-14_popcnt  -  AsmFishW_2018-02-19_popcnt
PGN-Datei: C:\Users\x\Desktop\Arena\Tournaments\187.pgn
Nr:  W/S 1/2     W:S       1:2           Uhrzeit      Wert Züge   Tief 1:2       1-2-Remis
   1 W 1   1,0:0,0       1,0:0,0       07:56:36   +15.79    52  18,867 :11,759  1-0-0
   2 S 1    2,0:0,0        2,0:0,0       07:57:31   -49.61    61   18,907 :11,791  2-0-0
   3 W 1   3,0:0,0       3,0:0,0       07:58:11   +17.66    46  19,068 :11,986  3-0-0
   4 S 1    4,0:0,0        4,0:0,0       07:58:53    -9.46     51   18,957 :11,826  4-0-0
   5 W 1   5,0:0,0       5,0:0,0       07:59:24      +M8    36  18,813 :11,820  5-0-0
   6 S 1    6,0:0,0        6,0:0,0       07:59:52   -10.44    33  18,835 :11,805  6-0-0
   7 W 1   7,0:0,0       7,0:0,0       08:00:29     +M24   43  18,746 :11,751  7-0-0
   8 S 1    8,0:0,0        8,0:0,0       08:01:12   -56.25    50   18,774 :11,774  8-0-0
   9 W 1    9,0:0,0       9,0:0,0       08:01:48      +M4    44  18,659 :11,716  9-0-0
  10 S 1    10,0:0,0     10,0:0,0      08:02:28   -55.90    46  18,646 :11,752  10-0-0
  11 W 1   11,0:0,0    11,0:0,0      08:03:13   +15.65    50  18,614 :11,731  11-0-0
  12 S 1    12,0:0,0     12,0:0,0      08:03:55   -11.81    48  18,572 :11,703  12-0-0
  13 W 1   13,0:0,0     13,0:0,0      08:04:30   +12.82   41  18,506 :11,688  13-0-0
  14 = =   13,5:0,5     13,5:0,5      08:05:07     0.00     40  18,565 :11,687  13-0-1
  15 W 1   14,5:0,5     14,5:0,5      08:05:52    +M12   50  18,579 :11,644  14-0-1
  16 S 1    15,5:0,5     15,5:0,5      08:06:42     -M22    58  18,597 :11,615  15-0-1
  17 W 1   16,5:0,5     16,5:0,5      08:07:30   +56.08   56  18,596 :11,587  16-0-1
  18 S 1    17,5:0,5     17,5:0,5      08:08:38   -54.52     81  18,693 :11,598  17-0-1
  19 W 1   18,5:0,5     18,5:0,5      08:09:23   +23.09   54  18,659 :11,572  18-0-1
  20 = =   19,0:1,0     19,0:1,0      08:11:04     0.00    110  18,664 :11,559  18-0-2

Engine-Match Montag, 19. Februar 2018 08:21:21
Paarung 1/1 :    AsmFishW_2018-02-19_popcnt  -  AsmFishW_2017-08-14_popcnt
PGN-Datei: C:\Users\x\Desktop\Arena\Tournaments\188.pgn
Nr:  W/S 1/2     W:S       1:2           Uhrzeit      Wert Züge Tief 1:2       1-2-Remis
   1 S 2      1,0:0,0        0,0:1,0       08:22:06   -57.00    65  11,219 :11,452  0-1-0
   2 = =     1,5:0,5        0,5:1,5       08:22:47     0.00     61  11,204 :11,547  0-1-1
   3 = =     2,0:1,0        1,0:2,0       08:23:35     0.00     71  11,210 :11,684  0-1-2
   4 S 1      3,0:1,0        2,0:2,0       08:24:21   -15.00    72  11,202 :11,781  1-1-2
   5 W 1     4,0:1,0        3,0:2,0       08:24:59   +58.82   55  11,255 :11,669  2-1-2
   6 W 2     5,0:1,0        3,0:3,0       08:25:28   +12.29   49  11,355 :11,746  2-2-2
   7 S 2      6,0:1,0        3,0:4,0       08:26:10   -52.73    74  11,304 :11,649  2-3-2
   8 = =     6,5:1,5        3,5:4,5       08:26:55     0.00     71  11,261 :11,621  2-3-3
   9 = =     7,0:2,0        4,0:5,0       08:27:28     0.00     48  11,229 :11,569  2-3-4
  10 = =    7,5:2,5        4,5:5,5       08:27:46     0.00     41  11,241 :11,591  2-3-5
  11 W 1    8,5:2,5        5,5:5,5       08:28:08   +20.87   60 11,220 :11,571  3-3-5
  12 = =    9,0:3,0        6,0:6,0       08:28:30     0.00     52  11,207 :11,554  3-3-6
  13 S 2     10,0:3,0       6,0:7,0       08:29:25   -56.38   73  11,174 :11,518  3-4-6
  14 W 2    11,0:3,0       6,0:8,0      08:30:10    +9.42   76  11,166 :11,490  3-5-6
  15 = =    11,5:3,5       6,5:8,5      08:30:38     0.00     37  11,177 :11,493  3-5-7
  16 W 2    12,5:3,5       6,5:9,5      08:31:20   +13.55   64  11,194 :11,475  3-6-7
  17 W 1    13,5:3,5       7,5:9,5      08:31:59   +48.46   59  11,204 :11,499  4-6-7
  18 = =    14,0:4,0       8,0:10,0    08:32:39     0.00     63  11,187 :11,468  4-6-8
  19 W 1    15,0:4,0       9,0:10,0    08:33:29   +49.63   77  11,171 :11,457  5-6-8
  20 W 2    16,0:4,0       9,0:11,0    08:34:12   +13.54   60  11,199 :11,465  5-7-8

I can not say more than that. Now it's her turn.

**Comment by lantonov** [comment]
@jjustine 
I believe there is some problem in the settings which is possible to be due to asmFish and not to the GUI. I have to think for some test which may help to pinpoint the problem more exactly. Your results in Arena point to the implementation of Minimum Think Time as the probable culprit. It is, however, known that Arena is not the best GUI to test for time management, as the GUI itself steals parts of a second from each move for its own process execution. 
Using a GUI with a chronometer and a carefully planned timing for the test and then comparing AF and SF (Cfish, Brainfish) for their time usage with minthinktimes of 0 and 5000 (min and max) would be more revealing.
Some mistake in the code restoring the old time management is not excluded. As far as I can tell, comparing the asmFish code prior to the TM change (Aug 14) and the latest code restoring the old TM (Feb 15), I couldn't find any difference. But indeed, maybe Moha with his much better trained eye could be able to spot something amiss.

**Comment by ghost** [comment]
Hi lantonov and Counterply
I think I have found a solution after I've looked at a few relevant .asm files in the source. Namely, I noticed the following: there is the entry in MainData.asm in line 83: db 'option name MinThinkTime type spin default 0 min 0 max 5000'. For example, I changed the default 0 value to 400 and saved the file. Then I changed in the Uci.asm in the line 11: mov dword [rdx + Options.minThinkTime], 0 the value 0 also to 400 and save the file. After that I created the asmFishW_2018-02-19_popcnt with make.file and fasmg. Then I installed this in Arena. In the settings, the 400ms were already set and I did a test again against asmFishW_2017-08-14_popcnt. Both were set to 400ms and the result was great. AsmFishW_2018-02-19_popcnt wins 6.0: 4.0 in a short test. The depth is at both 18-20.
Unfortunately you always have to change the values minThinkTime ​​in the Uci.asm and the MainData.asm if you need another minthinktime. But it's all ok. Perhaps you can try to simplify something else so that you can set directly on the GUI (Arena), because that is unfortunately not yet at the moment.  But I can play with the engine and that's the main thing. The new Asmfish is strong!

Engine Match Monday, February 19, 2018 14:37:34
Pairing 1/1: AsmFishW_2017-08-14_popcnt - AsmFishW_2018-02-19_popcnt
PGN file: C: \ Users \ x \ Desktop \ Arena \ Tournaments \ 190.pgn

No: W / S 1/2 W: S 1: 2 Time Value Trains Low 1: 2 1-2-draws
  1 = = 0.5: 0.5 0.5: 0.5 14:38:28 0.00 47 19.463: 20.425 0-0-1
  2 W 2 1.5: 0.5 0.5: 1.5 14:41:08 + 52.48 153 18,934: 19,382 0-1-1
  3 = = 2.0: 1.0 1.0: 2.0 14:41:21 0.00 11 18.973: 19.381 0-1-2
  4 S 1 3.0: 1.0 2.0: 2.0 14:42:21 -48.59 55 18.940: 19.222 1-1-2
  5 = = 3.5: 1.5 2.5: 2.5 14:44:34 0.00 113 18.808: 19.152 1-1-3
  6 = = 4.0: 2.0 3.0: 3.0 14:45:59 0.00 68 18.738: 18.973 1-1-4
  7 = = 4.5: 2.5 3.5: 3.5 14:46:56 0.00 47 18.790: 18.945 1-1-5
  8 W 2 5.5: 2.5 3.5: 4.5 14:48:24 +47.71 77 18.881: 18.968 1-2-5
  9 S 2 6.5: 2.5 3.5: 5.5 14:50:17 -10.97 101 18.804: 18.868 1-3-5
 10 = = 7.0: 3.0 4.0: 6.0 14:52:16 0.00 108 18.864: 18.849 1-3-6

**Comment by lantonov** [comment]
Hi jjustine,
What you have done is much more illuminating and point more definitely to problems with the new code. There has to be some place in that reflects the change in Uci.asm to action of this changed value. I had time for only a cursory look in the new code and maybe I have missed this place. Today, I started a deeper look in the new code and already identified 3 lines that differ between the direct and reverse changes. They don't include the value minThinkTime and are possibly not related to this bug but still ... . I have to check if these are not related to some subsequent change. The problem is that shortly after the commit with the TM change (Aug 14), on Aug 16 Moha rewrote completely the asmFish code for the fasmg assembler (before it was fasm assembler) and this very extensive rewrite was started anew as an initial commit (bulk files). This requires a comparison between 3 sources, Aug 14, Aug 16, and Feb 19 '18

**Comment by ghost** [comment]
Hi lantonov,
yes, I also think that maybe other things play a role. Take your time and look in peace to see if any improvements are needed and then bring out a new master. It's just not easy to switch to the OTM after half a year with the NTM, that's normal. I am satisfied for my part and can play with the new master. I thought about linking the Uci.asm in line 11 directly to MainData.asm in line 83. So you can perhaps directly change the settings of the GUI, the value changes automatically in the UCI and by the link in the MainData.asm which is probably not the case at the moment. But this is just a vision of me and unfortunately I can not put this into action because I do not speak the programming language. Thank you.

**Comment by lantonov** [comment]
option.minThinkTime is found in the latest code in 3 places in TimeMng.asm (lines 31, 78, 89) and in 2 places in Uci.asm (lines 11 and 989). I have further to check the occurrences in the other 2 sources and compare them. Further, minThinkTime is connected within a formula with optimumTime which should also be checked. 
Have to check also if the other options, especially SlowMover and MoveOverhead, work because they are implemented in a similar way.

**Comment by lantonov** [comment]
In this section of code in Uci.asm:963
```assembly
.MultiPv:
           call  ParseInteger
  ClampUnsigned  eax, 1, MAX_MOVES
            mov  dword[options.multiPV], eax
            jmp  UciGetInput
.Chess960:
           call  ParseBoole
            mov  byte[options.chess960], al
            jmp  UciGetInput
.Ponder:
           call  ParseBoole
            mov  byte[options.ponder], al
            jmp  UciGetInput
.Contempt:
           call  ParseInteger
    ClampSigned  eax, -100, 100
            mov  dword[options.contempt], eax
            jmp  UciGetInput
.MoveOverhead:
           call  ParseInteger
  ClampUnsigned  eax, 0, 5000
            mov  dword[options.moveOverhead], eax
            jmp  UciGetInput
.MinThinkTime:
            call  ParseInteger
  ClampUnsigned  eax, 0, 5000
            mov  dword[options.minThinkTime], eax
            jmp  UciGetInput
```
we see that several options including .MinThinkTime pass execution to the subroutine UciGetInput. As the name shows, this subroutine should take the user input and pass the respective value for further processing. All these options a coded in a very similar way so if there is some problem in this code or in UciGetInput, all these options should be affected.
I found some code which was removed in Aug'17 and was not restored in Feb'18:
```assembly
		lea   rcx, [sz_minthinktime]
	       call   CmpStringCaseless
		lea   rbx, [.MinThinkTime]
	       test   eax, eax
		jnz   .CheckValue
```
For the moment, I don't know if this is needed and could be an issue. Maybe there is an explanations or it is implemented elsewhere. In any case, a test with this code included is in order.

**Comment by ghost** [comment]
Hi,
ok thank you.
What does it mean in plain text now? Is it ok for the next master?
As I said, if this should cause other problems, then leave it to the old. I can now change the values directly via the Uci.asm and the Data.asm. It's awkward because you have to compile again, but that's fast. I'm just making two asm_popcnt. One I leave original and in the other I change the values. Of course you should now clean up and test the problem in this early phase of the "OTM" before it could eventually affect other parts of the Source. It's your decision, of course. Please tell me again if you are doing a new Master. Thank you.

**Comment by lantonov** [comment]
I can make a test executable with the above code included without necessarily changing the official master. I can upload it somewhere for you to test (tell me what you prefer - Windows, Linux, bmi2, popcnt, base, etc.). If this test version behaves well and responds to changing the option, it then comes in the official master as a bug fix. I strongly suspect that this is the missing code because it is exactly in the procedure for setting options. There are several places in this area that differ considerably from the original OTM and these may affect other options, too. For example, SlowMover is very truncated and it is possible that Slow Mover doesn't work, either. So you can test for these options, too, in Arena. There is a comment there for Clear Hash which is specific for Arena. I don't think that adding this code would affect other parts of the source. But it will show ...

**Comment by ghost** [comment]
Yes that is a good idea. I have Windows 7 64 bit and always play with the popcnt.

**Comment by lantonov** [comment]
You can find the test version [here](https://github.com/lantonov/asmFish/blob/executables/Windows/asmFishW_2018-02-20_popcnt.exe)
Seems to be working. In Winboard I tested this executable in 60 sec + 0 games. The first engine had 0 MinThinkTime and the second had 5000 MinThinkTime. The second engine always lost on time while the first engine had 44 sec on the clock.

**Comment by ghost** [comment]
Perfect, I can set the MinThinktime in your downloaded and changed file directly in Arena Settings, the MinThinkTime to any value between 0 and 5000 it works. I downloaded your current master this afternoon and changed the values ​​in the uci and Maindata.asm. I renamed this file _400ms and let it play against your just downloaded in a small tournament. And the result clearly shows that both work with 400ms. And it's nice that the changes in your gameplay have made it the same.

Engine Match Tuesday, February 20, 2018 21:23:56
Pairing 1/1: AsmFishW_2018-02-20_400ms - AsmFishW_2018-02-20_popcnt
PGN file: C: \ Users \ x \ Desktop \ Arena \ Tournaments \ 229.pgn

No: W / S 1/2 W: S 1: 2 Time Value Trains Low 1: 2 1-2-draws
   1 = = 0.5: 0.5 0.5: 0.5 21:25:37 0.00 88 20,000: 20,661 0-0-1
   2 = = 1.0: 1.0 1.0: 1.0 21:26:42 0.00 57 19,593: 19,849 0-0-2
   3 = = 1.5: 1.5 1.5: 1.5 21:30:37 0.00 201 19.390: 19.631 0-0-3
   4 = = 2.0: 2.0 2.0: 2.0 21:31:18 0.00 35 19.785: 19.827 0-0-4
   5 = 2.5: 2.5 2.5: 2.5 21:32:18 0.00 53 19,685: 19,691 0-0-5
   6 = = 3.0: 3.0 3.0: 3.0 21:33:36 0.00 67 19.529: 19.534 0-0-6
   7 = = 3.5: 3.5 3.5: 3.5 21:35:01 0.00 71 19.416: 19.417 0-0-7
   8 = 4.0: 4.0 4.0: 4.0 21:37:19 0.00 108 19.338: 19.309 0-0-8
   9 = = 4.5: 4.5 4.5: 4.5 21:39:15 0.00 85 19.309: 19.335 0-0-9
  10 = = 5.0: 5.0 5.0: 5.0 21:39:31 0.00 14 19.375: 19.386 0-0-10

Of course, I only play until max ~ 400-500ms when I play a small fast tournament with the other engines. Otherwise, the 20ms remains. But I can now switch directly back to Arena and that's the point. So problem solved. There you can update the current master. Thank you.
