### ISSUE TITLE
new asmFish version BMI2 crashes when trying to load a polyglot book file

### ISSUE THREAD

**Issue by ghost** [lantonov/asmFish#151]
Hello, I want to report that the latest asmFish I've just compiled crashes on playchess, telling "book.bin" couldn't be loaded. Now, trying with Fritz 16, a popup window comes out telling "asmFish caused an exception...
![caused an exception](https://user-images.githubusercontent.com/33367597/38396456-b4caf248-3927-11e8-8a2c-c6b3a048569f.jpg)

**Comment by CounterPly** [comment]
There is no such thing as "compiling" asmFish (assembly is a machine-level language), so I assume that you mean that you attempted to "assemble" it with the makefile.

In any case, plenty of users have been able to successfully load and use polyglot .bin books, so this is probably an issue on your end. Furthermore, Book.asm hasn't been touched in over 2 months, so there is no reason you should be experiencing problems now.

Try using the pre-assembled executables instead. Here is the bmi2 link: https://github.com/lantonov/asmFish/raw/master/WindowsOS_binaries/asmFishW_2018-04-01_bmi2.exe

**Comment by ghost** [comment]
With the executable you provide it's working flawless, thank you very much. What about the possible less performance of using a pre-assembled version instead of using a local assembled one? If I recall correctly the main goal of the asmFish package was to provide the source to make users compile themselves... I really don't know what happened, I've just click the bat file inside the package and press the B button for BMI2 executable assembling.

**Comment by CounterPly** [comment]
I am glad to hear it works for you. I'll look into the BMI2 option in make.bat at some point to see if anything is off there.

Regarding your question, there is no "performance boost" for assembling locally. You are still confusing "compiling" with "assembling." An assembler translates assembly code to machine code. The translation is mechanical, and can be done in only one way. In contrast, a compiler has more freedom when it compiles the relevant programming language - it can optimize, for example, and even non-optimizing compilers produce different code. Also, compilers can be written in a way that separates the "front-end" (corresponding to the programming language) and the "back-end" (corresponding to the computer architecture), whereas with assemblers the two are always the same.

Bottomline: there are no "Profile-Guided Optimizations" during the assembly process because the whole point to assembly is that the human, and not a compiler, defines "optimizations" (i.e. register allocation, speed optimization, etc). The optimizations you are thinking of are only associated with engines that actually require a compiler, like Stockfish or Cfish.
