### ISSUE TITLE
what is bmi1 & bmi2  (question)

### ISSUE THREAD

**Issue by sohel1214** [lantonov/asmFish#212]
when i try  bmi 1 and bmi2 not active engine but only popcent ok. pls tel . where is prob my pc

**Comment by CounterPly** [comment]
I am not sure I fully understand your question, but bmi1 and bmi2 are processor specific "Bit Manipulation Instruction" sets.

For intel products, there is no such thing as a "bmi1 only" processors since all bmi-capable processors support bmi2 which by default includes all bmi1 instructions. For some AMD processors, however, there is support for bmi1 instructions but NOT bmi2.

**Comment by MichaelB7** [comment]
@sohel1214
I’m guessing you are saying popcnt works and bmi exe’s do not work on your machine.  bmi exe’s will only work if your processor supports the bmi instruction set. Just use the version tht works for you.

**Comment by sohel1214** [comment]
tks for reply , i get it clr if processor not support then not work engine . 1 ques more which engine best for play . popcnt or bmi .

**Comment by MichaelB7** [comment]
Functionally , they are the same , so which one is best depends on your hardware. If both work , start stockfish on the commandline and type “bench” whichever one provides you with the highest nps ( or shortest completion time ) would be best for your hardware.

**Comment by sohel1214** [comment]
open stockfish and paste banch its like that in the end ?
Total time (ms) : 3265
Nodes searched  : 5023629
Nodes/second    : 1538630

after that what i follow Total time (ms)  or Nodes searched or Nodes/second  ?
if total time 2200 then good for me or 3200 or 3200+ good for me pls tel me.
same Nodes searched  : 5023629 good for me or 40 gd for me
Nodes/second    : 1538630 gd for me or 10 gd for me
