### ISSUE TITLE
Windows performance on 8-node machine

### ISSUE THREAD

**Issue by CoffeeOne** [lantonov/asmFish#43]
Hello,
I noticed that Asmfish has slower nodespeed on 64Cores/8 Numa Nodes than CFish, Asmfish shows about 50000kN/s, where Cfish has 60000+kN/s. It's strange because single thread performance is higher for AsmFish.
Are you interesting in finding out the reason?
If yes, I would suggest, that I make several bench runs for CFish (latest version January this year) and compare it with AsmFish from this time, for 1 thread, 2, threads, 4, 8, 16, 32, 64, or whatever you suggest.
Also in CFish there is a possibility to turn off NUMA functionality, so I could also make bench runs when NUMA is turned off.
best regards

**Comment by tthsqe12** [comment]
there are a myriad of hypotheses
1) march stockfish has decreased nps from jan stockfish
2) cfish on your machine may use lzcnt instead of bsf
3) lzcnt may have a higher throughput but similar latency
4) asmfish is tuned for single-threaded performance and might take greater advantage of the OoOE capabilities of your processor
5) bulldozer's OoOE might suffer when saturated with threads
6) asmfish's funny way of updating hash entries might not play nice on your machine with many threads
7) cfish may have a magical chakra alignment

I don't really see this as addressable by me as I only have a lowly 4700 and no need to upgrade.
Once you have addressed 1, you could see if 2+3 or 4+5 is the issue by running both engines with 32 threads and 4 threads on each node pair. As far as I know, Cfish has this capability. In asmfish, it is
setoption name nodeaffinity value 0 2 4 6
setoption name threads value 32
isready
if nodes 0 and 1 are the fused bulldozer cores, 2 and 3, ect.
Also, if you send me the executable you are using, I can check if 2 is true.

**Comment by CoffeeOne** [comment]
Thx for answering, I wrote a response to your private email address, maybe we can arrange a teamviewer session.
