### ISSUE TITLE
Support for Gaviota Tablebases 

### ISSUE THREAD

**Issue by Nordlandia** [lantonov/asmFish#44]
I find depth to mate format still useful for Fritz 15's "Let's Check Analysis" and particularly endgame studies since majority ignores 50-move rule. 

This will be nice addition for endgames and studies. 

https://chessprogramming.wikispaces.com/Gaviota+Tablebases

Article from magazine EG on 50-move rule for studies: http://pasteboard.co/1MHlyXZuy.png

**Comment by lantonov** [comment]
If the 50-move rule is the main reason for not using Syzygy and preferring Gaviota/Nalimov you have the option in SF and asmFish
`option name Syzygy50MoveRule type check default true`
In GUIs you have the respective check box to turn 50-move rule on or off.
The problem with moves-to-mate is more difficult with syzygy but usually when a mate is found by syzygy and designated as 128.xx (-128.xx) the main evaluation algorithm takes up and this displays moves-to-mate of the main variation (such as M24, etc.).
Examples of mates of more than 50 moves (as many as 100 moves) found by SF/AF + Syzygy in problems with fortresses designated as draws in books you can find [here](http://www.talkchess.com/forum/viewtopic.php?t=55414)
I leave the final say to Moha, but I think adding Gaviota/Nalimov is not needed much in the time when other places remove those in favour of syzygy, see e.g. [here](http://www.talkchess.com/forum/viewtopic.php?t=63674)

**Comment by Nordlandia** [comment]
«For Endgame Studies»	

If you ask me... mate in x number of moves is better than standard 128.xx ->

I prefere to get an engine that gives : 
1) A better evaluation e.g. "mate in 25" instead of "+35.00" 

Much appreciated anyway.

**Comment by Nordlandia** [comment]
Lantonov ->

Is it fairly easy or difficult to programme gaviota source code into asmfish.

I.e like copy paste & job done.

**Comment by lantonov** [comment]
Gaviota's algorithm is much different than Syzygy's. It would need 1-3 additional files of the sort of Tablebases*.asm containing several hundreds lines of code. In addition, search should be scheduled so that the engine has to divide resources and time for probing the two tablebases. The engine must also know (additional algorithms) how to compare evaluations from the two tablebases and how to prioritise this information.
In any case, search would slow down with this additional code.

**Comment by Nordlandia** [comment]
Probing Gaviota is meant for miscellaneous usage only.  Gaviota can be selected (Syzygy by default) see picture link. 

It was not my intention to mix Syzygy with Gaviota. Each format work seperately (by selecting format). 

https://cdn.pbrd.co/images/28whuXS3N.png

Is Moha often around here?

**Comment by tthsqe12** [comment]
If Nordlandia only wants a DTM, then this function (ProbeDTM) can be made from the existing ProbeWDL and ProbeDTZ.

**Comment by lantonov** [comment]
IMO, most of the things she wants can be made with the existing syzygy setup (see above). I opposed because I think it's not worth it for you to waste so much time for a marginal benefit. But you have the final say, of course.

**Comment by Nordlandia** [comment]
ProbeDTM is new for me. Do it involve evaluation to be converted/calibrated into DTM instead of 128.xx ?

**Comment by tthsqe12** [comment]
when the root is in the tbs, "ProbeDTM" means "use the tbs to find the shortest mate while completely ignoring the 50 move rule". I will see if this can be done in a reasonable amount of time even for the longest mates. You can find the same thing at
https://syzygy-tables.info/

**Comment by Nordlandia** [comment]
If ProbeDTM only works with 6 pieces or less ->

Just want to mention that Fritz Let's Check Database is connected to 6-men Nalimov EGTBs once position is in (egtb territory) root position.  Every position up to 6-pieces is already precached in let's check database with optimal result. 

Precisely DTM need to be available during the search, beside from already solved egtb territory.

I think, therefore it will be easier to add Gaviota format.

**Comment by Nordlandia** [comment]
Highlighted ->

https://cdn.pbrd.co/images/3LouQcRUH.png

![let s check](https://cloud.githubusercontent.com/assets/26534454/25002041/8c7cc4ae-2048-11e7-8590-c8637f9bab6c.png)

**Comment by Nordlandia** [comment]
Chiron 4 added most egtb formats and let user choose which format to use. 

For asmfish «Tablebase Usage» need to be everywhere, If it can be done.

![chiron](https://cloud.githubusercontent.com/assets/26534454/25061149/4735bbb2-21b0-11e7-88d2-f851605fe0ae.png)

**Comment by tthsqe12** [comment]
So I think this is quite a difficult request and quite unlike the other feature requests which can be quickly dispensed with.
As I understand it, the gaviota tbs store DTM while the syzygy tbs store DTZ+WLD. In terms of playing strength, the syzygy tbs are in no way inferior to gaviota tbs. Therefore, I would like to keep the engine using RdM's syzygy tbs only. Also, syzygy is smaller and and goes up to 6 men.

The only problem with syzygy is that stockfish might not find the shortest win, as is clear from several endgames of stockfish in TCEC where the engine played moves that win, but prolong the game because the search is not able to find the mate. This is purely an aesthetics issue. This is also probably the source of this issue
https://github.com/lantonov/asmFish/issues/45

Probing the gaviota tbs will involve importing a ton of code. There is another option of using DTZ and WLD information to generate the DTM figure. However, this will involve some search and is not completely straight-forward. Maybe someone here can comment on the following psuedo code:
```
assuming the side to move is winning according to WDL syzygy, you would call
searchDTM(rootpos, 1)
searchDTM(rootpos, 2)
searchDTM(rootpos, 3)
ect
in a loop to get a better and better upperbound on the DTM score.
There could also be many heuristics to sort the moves in search and qsearch

proc searchDTM(pos p, depth d):
	assert(is_tb_win(p))	// pos is winning for the side to move
	score s = INFINITY		// we have a mate in a large number of moves
	assert(not_empty(legal_moves(p)))
	for each ourmove in legal_moves(p)
		do_move(p,ourmove)
		if is_3fold_draw(p) or not(is_tb_loss(p))
			undo_move(p,ourmove)
			continue
		end if
		assert(is_tb_loss(p))
		score t = 0
		for each theirmove in legal_moves(p)
			do_move(p, theirmove)
			score u
			if d>1
				u = searchDTM(p, d-1)
			else
				u = qsearchDTM(p)
			end if
			t = max(t, u)
			undo_move(p, theirmove)
		end for
		s = min(s, t+1)
		undo_move(p,ourmove)
	end for
	assert(s != INFINITY)
	return s
end proc

proc qsearchDTM(p):
assert(is_tb_win(p))
// find _any_ line that leads to mate and return its length
// the point is to get an upper bound on the DTM score
end proc
`

**Comment by Ipmanchess** [comment]
I would contact Ronald de Man..he can give his idea about this!

**Comment by tthsqe12** [comment]
oh I can see that that algo is not going to work at all.
If anyone has ideas on how to use DTZ+WDL to get DTM that would be helpful.

**Comment by lantonov** [comment]
You can look into this[ idea of Prof. Michel van der Bergh](https://groups.google.com/forum/?fromgroups=#!topic/fishcooking/Fh9MuUldyF0). He proposes use of only syzygy but continuing normal search after syzygy finds mate and displays 128.xx

**Comment by Ipmanchess** [comment]
That's maybe a good idea..if syzygy gives for example +20 ,it's a winning game ..shut off syzygy and engine can show a Mat score..in place to let it continue and showing +128..
But what about the 50-moves rule..it still count the moves further?!

**Comment by lantonov** [comment]
For 50-moves rule you always have the option `setoption name Syzygy50MoveRule value false`

**Comment by hero2017** [comment]
In addition, when running infinite analysis in a gui like Aquarium you don't have the option to disable/enable Syzygy. You have to actually delete the syzygy path just to disable syzygy.

Can we have a simple checkbox/radiobox to enable/disable Syzygy in the engine parameters (like Komodo has)? We already have this to enable/disable the 50-move rule so. It'd be so much easier to enable/disable syzygy with the same method because the next time I want to enable Syzygy I have to copy/paste 3 separate paths separated by a ";" which is a pain when you're switching on/off often during analysis.

I wish SF would finally add this option. I don't think I'm asking for too much. Surely I'm not the only one who has to go through this anguish.

Let me know if I should repost this as a separate feature request. Thanks in advance.

**Comment by lantonov** [comment]
Let's put [this solution](https://github.com/jhellis3/Stockfish/commit/02b4b24a0419c5c84b5efe9ad9905816f7ade6d7) from Joseph Ellis' Matefinder in our Matefinder but not in asmFish so not to disturb bench and do away with all that.

**Comment by lantonov** [comment]
These discussions about "Natural TB" are highly relevant to the issue:
http://talkchess.com/forum/viewtopic.php?t=60312
https://groups.google.com/forum/?fromgroups=#!topic/fishcooking/2k6Pw_yZfbk

**Comment by Nordlandia** [comment]
Ronald is currently generating syzygy depth-to-mate. Estimated size for 6-men ~ 500 GB +/-
