### ISSUE TITLE
mateFish name

### ISSUE THREAD

**Issue by maelic13** [lantonov/asmFish#68]
I know this is no real problem with the engine but the GUI itself but it seems like any engine which name starts with 'mate' is not shown in engine options under Fritz 15 GUI so mateFish cannot be used.
I am using a temporary name 'killFish' but it sounds silly..

**Comment by lantonov** [comment]
I am reluctant to change the name "mateFish" not because of the effort which is minimal but because of:
1. I fail to come up with a better name which still includes Da Fish (suggestions are welcome though)
2. not accepting any engine whose name starts with 'mate' is a serious bug in Fritz 15 GUI and I don't like to encourage ChessBase neglecting it

**Comment by maelic13** [comment]
I fully understand your position - Chessbase really should resolve this problem themselves. It is just a bit annoying for the users.
Thank you for your work!
