### ISSUE TITLE
 Cerebellum compatibility

### ISSUE THREAD

**Issue by tzipproth** [lantonov/asmFish#79]
I'm planning to make a direct release of Cerebellum_light for asmFish in the Polyglot book format.
There is only one book feature missing in asmFish which makes this a bit complicated.

There is no handling of repetitions in the book itself  as far as I can see in the code.
This can lead to more direct draws than necessary, even in positions with an advantage.
I'm not sure how this problem is handled in other book formats like ctg, maybe there are reasons that it is not necessary at all.

Because Cerebellum is calculated automatically, repetitions occur more frequently when for example moves have an identical score. Therefore their handling is more important.

I describe the algorithm used in Brainfish:

If the engine sees that the first book move leads to a position which already occured in the game, the following is done:

1. The engine looks if there is a second move in the book (in Cerebellum_light only one or two playable moves for every positions are directly in the book).
2. If there is no second move in the book, the first one which leads to a repetition is played, which includes the assumption, that there is no better one. (Perhaps there should be an option to start calculating instead).
3. If there is a second move which does not lead to a repetition, this move is played.
4. If the second move leads to a repeated position too, the engine starts calculating.

Perhaps something like this can be implemented in asmFish too.

**Comment by lantonov** [comment]
Thomas, thanks for your intention to make an asmFish-compatible version of Cerebellum_light which I consider a wonderful idea. So far we have the facility in asmFish to transform the Cerebellum books in Polyglot format by the procedure described in https://github.com/lantonov/asmFish/blob/executables/Cerebellum/readme.txt. It involves first translating Cerebellum_light in pgn format and then transforming this pgn into polyglot bin format. This procedure is naturally slow and takes up to an hour on my computer. It would only become slower with a bigger book.
I use the obtained book as a gui book in Winboard because it has facilities to directly manipulate polyglot books. I have played many games with this setup in FICS, of which I have lost only 2 so far (I have sent you both lost games in e-mails). However, I have many drawn games (I can send you all my games in FICS if those can be of use).
About the issue raised in your post, I really find very exasperating when Cerebellum forcibly draws after 12-15 moves against a weaker opponent. Having a non-drawing move played in these cases would be a great improvement (though I haven't seen a second-best move in Cerebellum_light).
It would be great if @tthsqe12 can apply the Brainfish algorithm described by you.

**Comment by tthsqe12** [comment]
lantonov, if you set the depth to something reasonable like 40 or 50, you will get almost all entries and it should only take a few minutes. The algorithm has nothing to do with pgn and was not designed for depth 200. If you have an idea for exploring the whole book efficiently, let me know

**Comment by lantonov** [comment]
@tthsqe12, my fault again, I heard about pgn from someone else. I didn't want to say that the present Cerebellum setup does not work. On the contrary, it works for me and I use it extensively. Still, it would be great if we have a polyglot compatible Cerebellum for asmFish updated regularly and protected against early draws.

Translating latest Cerebellum with depth 50 takes 8 minutes. Updated Cerebellum Readme file with the smaller depth.

**Comment by ghost** [comment]
I want to contribute to the ASMfishW project but I do not know assembly language. 
How should I learn assembly language to help the project?

Also what would happen if it was re-coded in python or C++ or any other language?


Also how can I re-write ASMfishW to utilise GPU or CUDA processing? Is there a way to make ASMfish for FPGA or ASIC?


And how should I learn machine learning to help ASMfish neural network?

**Comment by lantonov** [comment]
@Dextro53, are you serious ?

**Comment by ghost** [comment]
Yes of course

**Comment by tthsqe12** [comment]
> I want to contribute to the ASMfishW project but I do not know assembly language. How should I learn assembly language to help the project?

I think you got it backwards. You should learn the project to help your assembly language. (assuming you want to learn assembly language). If you don't know assembly language, then there is not yet much you can contribute to the project that you couldn't contribute to stockfish project. If you want to learn assembly language, then this project will be difficult at the start. However, you will see how to communicate as directly as possible with your OS.

> Also what would happen if it was re-coded in python or C++ or any other language?

This question betrays your lack of knowledge on the stockfish project. Converting ASM -> HLL is not an easy process if you want readable HLL. On the other hand, HLL -> ASM is approachable and modern compilers do a decent job. Stockfish is written in C++ and this project is a humanistic attempt at the HLL -> ASM conversion.

> And how should I learn machine learning to help ASMfish neural network?

You will have to learn what a neural network is and how to train them. If you have some good ideas for incorporating a NN into a chess engine, Im sure many here would be interested, and some would be able to help you put that into code it this is a problem.

**Comment by tthsqe12** [comment]
> I'm planning to make a direct release of Cerebellum_light for asmFish in the Polyglot book format.

This is good. Hopefully this means that the brain2polyglot function can be removed now. It never worked the way I expected it to, maybe because of quirks in the Cerebellum_light book. But why is it "for asmFish"? Polygot format is widely used.

> There is no handling of repetitions in the book itself as far as I can see in the code.

That is correct. This code was made with the assumption that the book is acyclic. If the book contains cycles, I'm confident the current notion of negative book depth breaks down.

**Comment by lantonov** [comment]
But brain2polyglot function works as it is now. It translates Cerebellum in polyglot book and the latter can be used as any polyglot book, by the engine or by the GUI. I don't see what more can be expected of it except, of course, Cerebellum being itself polyglot with repetition handling.

**Comment by tzipproth** [comment]
"for asmFish" mainly means that it is identical to Cerebellum_Light for Brainfish, a restricted Demo Version of Cerebellum designed for the use in Engine games together with Stockfish. The full Version has much more Information and moves for every position but is still not available due to several unplanned delays.

Does the PGN converted Version have the second move for every position where it is in Cerebellum_Light? I could not see it in SCID. Without this second moves and the repetition handling there is no Variation in Cerebellum and it plays weaker. Without this  features I wouldn't call it Cerebellum at all.

It seems there are also some errors in the converted book. For example I could not see a correct move in Scid for positions with promotion moves like for example "r5k1/2Pb1p2/4n1p1/4p3/1NN1P3/3P3P/p4PP1/2RB2K1 b - -"

My intention to release a Cerebellum Version for asmFish is that I'm interested to see how the strongest stockfish Version plays in combination with Cerebellum, and that there is a correct Cerebellum version for this, not something that plays only similar to Cerebellum.

The reason of "quirks and cycles" in Cerebellum_light:

Cerebellum full was designed for the deep analysis of chess games and theory. Which means to finally know the truth in every position, if it is won or draw, and how the main variations are going.  This includes the fact that chess is a graph, not a tree, and therefore it naturally contains many possible cycles, mainly in draw positions with the score 0.00, but also in positions with an advantage it can happen.

Because it would be very elaborate to resolve all this cycles before generating Cerebellum_Light, I decided to let this handle the engine during play. Perhaps not the very best solution, but the best I could do in a restricted time. There is an option missing for strong engines to never repeat a position while beeing in the book, I might add this to Brainfish after some checks.

**Comment by tthsqe12** [comment]
Ah! If cerebellum_light contains cycles, then the brain2polyglot is not going to work like I expected. That is why it was so slow! Anyways, I hope we can get rid of this function soon...

**Comment by jdehorty1** [comment]
I understand the rationale for wanting to supplement asmFish with a fully functional version of Cerebellum_light (complete with the BookMove2 function), but why remove the brain2polyglot function altogether? The really nice thing about being able to convert cerebellum_light to polyglot format is that the user has the power to make a polyglot-compatible .bin file that can include cerebellum_light positions in addition to other sources (i.e. other .bin files via "polyglot merge-book" or the latest novelties from online games via "polyglot make-book").

PS: I realize this concept of a user-made "super .bin file" inherently violates tzipproth's original vision of an unadulterated Stockfish playbook generated purely from a graph algorithm, but the option is still nice to have nevertheless. In my experience, by routinely and systematically adding to the converted Cerebellum from other sources, there can be just as much, if not more, variety than what is found in the original Cerebellum_light file.

**Comment by tzipproth** [comment]
It's not my intention that the brain2polyglot function is removed, the decision if it is still usefull has to be made by the maintainers.

A directly created Cerebellum-polyglot book can of course still be edited and changed, and asmFish will still be able to play with such a changed book. The enhancement will only add some playing strength and possibilities, and every other polyglot book can still be used.

**Comment by jjoshua2** [comment]
I would love it if draw prevention could be added for all polyglot books, because I have a polyglot I made myself from a tree, and sometimes it wants to move back and forth before progressing, but when I converted to polyglot it leads to the possibility of draw since polyglot does not have move numbers and I don't want to draw as white at move 10.

**Comment by tthsqe12** [comment]
So I will add repetition detection to the book version.
It will work like this:
 - if all of the book moves lead to a repetition, then choose from all book moves.
 - if there is a book move that does not lead to a repetition, then choose from all the book moves that do not lead to a repetition.

BTW, the fasmg port of this project has been complete for some time and is at https://github.com/tthsqe12/asm

**Comment by lantonov** [comment]
@tthsqe12 , when I try to assemble asmFish with fasmg from within the new asm master branch, I get the message
flat assembler  version g.hwx32
Error: not enough memory to complete the assembly.
i7-7500U with Windows 10
the command is
fasmg "x86/fish.asm" "asmFish_bmi2" -e 1000 -i "VERSION_OS='L'" -i "VERSION_POST = 'bmi2'"
Maybe I am doing something wrong ?

I saw that among the other big changes, you have implemented all the latest SF patches. Can I try to transfer the fasmg port to this repository?

**Comment by tthsqe12** [comment]
the g in fasmq stands for "generic", and you can do some pretty fantastic things with this new genericity. Here, it looks like you forgot to set the include environment variable, so everything is going to blow up.
If you look at the linux makefile, you will see the "include" variable being set. I'm sorry I have not been able to make a windows makefile yet.
You should be able to do
`set include=x86\include\`
`fasmg "x86\fish.asm" "asmfish.exe"   -e 1000 -i "VERSION_OS='W'" -i "PEDANTIC = 1" -i "VERSION_POST = 'bmi2'"`
The PEDANTIC option has made a comeback because a chess960 position has make an appearance in the bench. If you want to verify the bench number, the PEDANTIC option will include a stupid and untested condition that fires in chess960.

If your processor speed is measured in GHz, the assembly time should be less then 30 seconds.
The `x86\include` directory contains the definitions of x86 assembly language, which are of course needed!

**Comment by lantonov** [comment]
With the above commands in Windows, it's ok. Assembled it in 16.8 sec with the message
flat assembler  version g.hwx32
5 passes, 16.8 seconds, 110592 bytes.

I also tried to assemble it within Linux for Windows with the command `make` and got the following
./fasmg: 1: ./fasmg: Syntax error: "(" unexpected
makefile:3: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by tthsqe12** [comment]
That looks strange. Obvious some things need to be worked out. I have included the output when I give it a `make` at the bottom here. Are you saying it is failing at the first file (the arm version)?
```
$ make
export INCLUDE="arm/include/"; ./fasmg "arm/fish.arm" "armFishL_2017-10-03_v8"         -e 1000 -i "VERSION_OS='L'" -i "VERSION_POST = 'v8'"
flat assembler  version g.hwx32
3 passes, 7.5 seconds, 128018 bytes.
export INCLUDE="x86/include/"; ./fasmg "x86/fish.asm" "asmFishL_2017-10-03_popcnt"     -e 1000 -i "VERSION_OS='L'" -i "VERSION_POST = 'popcnt'"
flat assembler  version g.hwx32
4 passes, 18.1 seconds, 112326 bytes.
export INCLUDE="x86/include/"; ./fasmg "x86/fish.asm" "asmFishL_2017-10-03_bmi2"       -e 1000 -i "VERSION_OS='L'" -i "VERSION_POST = 'bmi2'"
flat assembler  version g.hwx32
4 passes, 17.5 seconds, 107798 bytes.
export INCLUDE="x86/include/"; ./fasmg "x86/fish.asm" "asmFishW_2017-10-03_popcnt.exe" -e 1000 -i "VERSION_OS='W'" -i "VERSION_POST = 'popcnt'"
flat assembler  version g.hwx32
5 passes, 23.4 seconds, 115200 bytes.
export INCLUDE="x86/include/"; ./fasmg "x86/fish.asm" "asmFishW_2017-10-03_bmi2.exe"   -e 1000 -i "VERSION_OS='W'" -i "VERSION_POST = 'bmi2'"
flat assembler  version g.hwx32
5 passes, 22.4 seconds, 110592 bytes.
export INCLUDE="x86/include/"; ./fasmg "x86/fish.asm" "asmFishX_2017-10-03_base"       -e 1000 -i "VERSION_OS='X'" -i "VERSION_POST = 'base'"
flat assembler  version g.hwx32
4 passes, 19.0 seconds, 123591 bytes.
export INCLUDE="x86/include/"; ./fasmg "x86/fish.asm" "asmFishX_2017-10-03_popcnt"     -e 1000 -i "VERSION_OS='X'" -i "VERSION_POST = 'popcnt'"
flat assembler  version g.hwx32
4 passes, 17.7 seconds, 119495 bytes.
export INCLUDE="x86/include/"; ./fasmg "x86/fish.asm" "asmFishX_2017-10-03_bmi2"       -e 1000 -i "VERSION_OS='X'" -i "VERSION_POST = 'bmi2'"
flat assembler  version g.hwx32
4 passes, 17.3 seconds, 115399 bytes.
```

**Comment by lantonov** [comment]
Probably it has problems recognising the statement
`now := $(shell /bin/date "+%Y-%m-%d")`
Ok, I will try to make a "make.bat" file for windows

**Comment by lantonov** [comment]
makefile in the fasm repo gives essentially the same error, so the problem is in Linux for Windows bash:
```
./asmFish/fasm "asmFish/asmFishW_base.asm"      -m 50000 "Windows/asmFishW_2017-10-03_base.exe"
./asmFish/fasm: 1: ./asmFish/fasm: Syntax error: "(" unexpected
makefile:3: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by lantonov** [comment]
Sorry, we were some off-topic by my fault. I see that Stefan Pohl has connected already Cerebellum to asmFish in something called asmBrainFish and it kicks ass. 
So the planned asmFish repetition handling will add to a high ground.

**Comment by hero2017** [comment]
Is this asmBrainFish publicly available?

Also, how can I use asmFish with a cerebellum converted polyglot book in infinite analysis for correspondence play and avoid draw by repetition moves? Currently I use Scid and open my polyglot.bin book in it and play the top move which I believe is supposed to be the strongest move. But I came across a game I found recently that ended in a draw due to 3-fold repetition which exists in the polyglot book. I can see how this asmBrainFish would avoid repetitions in engine vs engine games using CuteChess gui for example but how to avoid repetitions with the cerebellum light converted polyglot book in correspondence chess? We have to manually recognized that we've already played the same position twice from the polyglot book so we just pick another move ourselves in Scid? Are we to play the 2nd best move from the polyglot book manually? I assume the book moves from the polyglot book in Scid lists them from best move to worst move. Scid shows only one book move but if you click "Opponent's Book" in Scid it expands and lists a bunch of alternative moves in the polyglot book.

**Comment by mausalimi** [comment]
the cerebellum polyglot book is here:

http://zipproth.com/index.html#Brainfish_download

stefan pohl used the standard asmfish with this book for testing.
>Testrun of asmBrainFish 170825 finished. asmBrainFish is asmFish 170825 using a polyglot-version of the latest Cerebellum-Library (not generated automatically by asmFish, but manually by Thomas Zipproth himself, to avoid move-loops and draws out of the Library (the polyglot-version, asmFish generates automatically, does not prevent these problems and plays weaker!)). 

http://www.sp-cc.de/index.htm

**Comment by lantonov** [comment]
Can there be any performance penalty if we make `SetDefault 1, USE_BOOK`

**Comment by tthsqe12** [comment]
There should be no performance penalty except for executable bloat.
The commit https://github.com/tthsqe12/asm/commit/ae1b440c9f16d14c6ff2c10b7533bc81490f64dc
should be good for books. However, @lantonov , I wish that you would not release a bunch of executables until I have tested the windows version. I downloaded the polyglot cerebellum book and the latest stockfish executable and ran them in a tournament in arena. I am on linux so asmfish runs only 14% faster than stockfish. Despite this, with the help of this book, the result so far is 11-1-46 in favour of asmBrainFish.

@tzipproth, I have taken your description and generalised it to general books. Your "perhaps ... option" in point 2 in covered by the BestBookMove option. See if the description in
https://github.com/tthsqe12/asm/blob/master/README.md#engine-options
agrees with your setting of the moves and weights in the polyglot format.

**Comment by lantonov** [comment]
Ok, I'll also do some testing on Windows and post the results here.
On Windows, latest asmFish is 18% faster than Stockfish.

stockfish-b364897 vs asmFish-2608ad8 100 games 60+0.6
result +7 -22 =71, -52.51 +/- 36.12 Elo
In an effort to avoid repeating openings, I decided to use the 2-move fishtest book on both engines. However, this is really a disservice to asmFish because the 2-move book contains a lot of wacky openings and it is extremely rare to reach a book position. Attaching the games
[results.txt](https://github.com/lantonov/asmFish/files/1367005/results.txt)
Next, I will try to use more fully the own books by running the match in Winboard and using own Cerebellum for asmFish and GUI performance.bin for Stockfish (performance.bin is a popular book which I find often against me in online chess sites). Both books will be put to full variety (100%).

**Comment by tzipproth** [comment]
@tthsqe12  thanks for implementing all these book options, from what I read in your description they are well designed and compatible with Cerebellum. I uploaded a new version of Cerebellum Polyglot which contains all necessary second moves. I will make some additional tests to see if everything works.

Brainfish will be changed to Polyglot book format in the next version, because I think it makes no sense to have two different books formats for Cerebellum.

@hero2017
Cerebellum_light was mainly designed for engine vs engine play, but of course you can study the main variations and look if they are suitable for your correspondence chess strategy.
